# Generated by Django 3.2.13 on 2022-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Объект A',
                'verbose_name_plural': 'Объекты A',
                'db_table': '"public"."test_a"',
            },
        ),
        migrations.CreateModel(
            name='TestB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Объект B',
                'verbose_name_plural': 'Объекты B',
                'db_table': '"public"."test_b"',
            },
        ),
    ]
